-- DEAD FILE — safe to delete.
-- The floor_snapshot() function was part of the old dine-in order model and is
-- not used by the counter-sale app. This file is kept empty because OneDrive
-- ACL prevents deletion from the CLI. Delete it manually when convenient.
